volumes:
  Blog-db:
services:
  Blog.db:
    image: postgres:latest
    container_name: Blog.db
    environment:
      - POSTGRES_DB=Blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - Blog-db:/var/lib/postgresql/data 
    ports:
      - 5432:5432
  blogs:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  blog.seq:
    image: datalust/seq:latest
    container_name: blog-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5431
      - 8081:80
  
